header_bg = "#EBDBB2"
border = "#A89984"
focus_border = "#076678"
focus_title = "#3C3836"
highlight_bg = "#076678"
highlight_fg = "#FBF1C7"
focus_bg = "#FBF1C7"
block_bg = "#FBF1C7"
feeds_bg = "#EBDBB2"
preview_bg = "#FBF1C7"
text = "#3C3836"
dim = "#928374"
status_ok = "#79740E"
status_err = "#9D0006"
accent = "#076678"
accent_alt = "#B57614"
