header_bg = "#282828"
border = "#665C54"
focus_border = "#458588"
focus_title = "#EBDBB2"
highlight_bg = "#458588"
highlight_fg = "#EBDBB2"
focus_bg = "#1D2021"
block_bg = "#1D2021"
feeds_bg = "#282828"
preview_bg = "#1D2021"
text = "#EBDBB2"
dim = "#928374"
status_ok = "#98971A"
status_err = "#CC241D"
accent = "#83A598"
accent_alt = "#D79921"
