header_bg = "#EEE8D5"
border = "#93A1A1"
focus_border = "#268BD2"
focus_title = "#073642"
highlight_bg = "#268BD2"
highlight_fg = "#FDF6E3"
focus_bg = "#FDF6E3"
block_bg = "#FDF6E3"
feeds_bg = "#EEE8D5"
preview_bg = "#FDF6E3"
text = "#657B83"
dim = "#93A1A1"
status_ok = "#859900"
status_err = "#DC322F"
accent = "#268BD2"
accent_alt = "#CB4B16"
selection_bg = "#EEE8D5"
