use crate::store::models::{Entry, Feed, Group};

#[derive(Debug, Clone)]
pub enum Action {
    LoadFeeds,
    LoadEntriesFiltered {
        feed_id: i64,
        unread_only: bool,
        saved_only: bool,
    },
    SearchEntries {
        feed_id: Option<i64>,
        query: String,
    },
    RefreshFeeds,
    RefreshUnreadCounts,
    FeedsLoaded(Vec<Feed>),
    EntriesLoaded(Vec<Entry>),
    SelectFeed(Option<i64>),
    SelectEntry(Option<i64>),
    FocusEntries,
    FocusPreview,
    FocusFeeds,
    AddFeed {
        title: Option<String>,
        url: String,
    },
    DeleteFeed(i64),
    MarkRead(i64),
    MarkUnread(i64),
    MarkSaved(i64),
    MarkUnsaved(i64),
    ToggleUnreadFilter,
    ToggleSavedFilter,
    SetSearchQuery(String),
    FocusNext,
    FocusPrev,
    MoveUp,
    MoveDown,
    PageUp,
    PageDown,
    ScrollTop,
    ScrollBottom,
    UpdateUnreadCounts(Vec<(i64, i64)>),
    UpdateTotalUnread(i64),
    SetStatus(String),
    ClearStatus,
    DbError(String),
    LoadGroups,
    GroupsLoaded(Vec<Group>),
    AddGroup { name: String },
    DeleteGroup(i64),
    RenameGroup { id: i64, name: String },
    AssignFeedToGroup { feed_id: i64, group_id: Option<i64> },
    ToggleGroupCollapse(i64),
    ResizePanel(i8),
    UpdateTotalEntryCount(i64),
}
